name: Backend CI

on:
  push:
    branches:
      - 'main'
    
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: qa

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: 'google-github-actions/auth@v3'
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
          workload_identity_provider: 'projects/${{ vars.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ vars.GCP_WIF_POOL }}/providers/${{ vars.GCP_WIF_PROVIDER }}'
          service_account: ${{ vars.GCP_SERVICE_ACCOUNT_NAME }}@${{ vars.GCP_PROJECT_ID }}.iam.gserviceaccount.com

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ vars.GCP_LOCATION }}-docker.pkg.dev

      - name: Build and push image
        env:
          GCP_LOCATION: ${{ vars.GCP_LOCATION }}
          GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
          GCP_REPOSITORY: ${{ vars.GCP_REPOSITORY }}
          GCP_IMAGE: ${{ vars.GCP_BACKEND_IMAGE }}
        run: |
          docker build \
            --platform linux/amd64 \
            -f backend/Dockerfile \
            -t ${GCP_LOCATION}-docker.pkg.dev/${GCP_PROJECT_ID}/${GCP_REPOSITORY}/${GCP_IMAGE}:${GITHUB_SHA} \
            backend

          docker push ${GCP_LOCATION}-docker.pkg.dev/${GCP_PROJECT_ID}/${GCP_REPOSITORY}/${GCP_IMAGE}:${GITHUB_SHA}